name: platform
description: "A Platform Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8

  # Updated firebase_analytics to match firebase_core compatibility
  firebase_analytics: ^11.4.1

  # Updated transitive dependencies to the latest compatible versions
  async: ^2.11.0
  boolean_selector: ^2.1.1
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.19.0
  fake_async: ^1.3.1
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  matcher: ^0.12.16+1
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.0
  source_span: ^1.10.0
  stack_trace: ^1.12.0
  stream_channel: ^2.1.2
  string_scanner: ^1.3.0
  term_glyph: ^1.2.1
  test_api: ^0.7.3
  vm_service: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and add assets to include images, etc.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment and configure fonts if custom fonts are used.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
